LineageOS-20:
  kernel:
    - git clone https://github.com/aldnazr/android_kernel_xiaomi_ginkgo.git -b main
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main clang
  config:
    - make O=out ARCH=arm64 defconfig
  build:
    - |
      ARCH=arm64 \
      CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" \
      CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi-" \
      make -j$(nproc --all) \
      LLVM=1 LLVM_IAS=1 \
      LD=ld.lld AR=llvm-ar NM=llvm-nm \
      AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip \
      O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable
